<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-FMC8G94" failures="2" tests="3" name="Default test(failed)(failed)(failed)" time="28.685" errors="0" timestamp="2023-01-06T21:00:54 IST">
  <testcase classname="TestCases.FaildTest" name="Test1" time="0.132">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FaildTest.Test1(FaildTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="TestCases.FaildTest" name="Test5" time="0.071"/>
  <testcase classname="TestCases.FaildTest" name="Test2" time="0.072">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FaildTest.Test2(FaildTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="TestCases.FaildTest" name="Test4" time="0.0">
    <ignored/>
  </testcase> <!-- Test4 -->
  <testcase classname="TestCases.FaildTest" name="Test3" time="0.0">
    <ignored/>
  </testcase> <!-- Test3 -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
